apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  contentgrid.test.server: |
    contentgrid.test:53 {
        errors
        hosts {
            172.17.0.1 api.contentgrid.test auth.contentgrid.test console.contentgrid.test
            fallthrough
        }
        forward . 127.0.0.1
    }
